eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:7700/eureka/
logging:
    config: classpath:logback.xml
server:
    port: 6604

spring:
    application:
        name: gateway-service
    cloud:
        gateway:
            filter:
                remove-non-proxy-headers:
                    headers:
                    - dummy
            routes:
            -  id: apiuser
               uri: lb://user-service
               predicates:
               - Path=/userapi/**
               filters:
               - StripPrefix=1
            - id: api2user
              uri: lb://user-service
              predicates:
              - Path=/userapi2/**
              filters:
              - StripPrefix=1

management:
  endpoints:
    web:
     exposure:
       include: "*"
